walshperu/platzigram/platzigram/urls.py
"""Platzigram URLs module."""

# Django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from biologia import views


urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('users/', include(('users.urls', 'users'), namespace='users')),

    #Avez Links
    path('biologia/form_coordenadas_aves/',views.form_coordenadas_aves, name='form_coordenadas_aves'),
    path('biologia/form_base_datos_avez/',views.form_BD_Avez_Chinalco, name='form_BD_Avez_Chinalco'),
    path('biologia/form_fotos_integrado_avez/',views.form_fotos_integrado_Avez_Chinalco, name='form_fotos_integrado_Avez_Chinalco'),

    #Anfivioz_Reptiles (BD) Links
    path('biologia/form_base_anfibios_reptiles/',views.form_anfibios_reptiles_base_datos, name='form_anfibios_reptiles_base_datos'),
    path('biologia/form_coord_anf_rep/',views.form_coordenadas_anfibios_repites_bd, name='form_coordenadas_anfibios_repites_bd'),
    path('biologia/form_hoja_1/',views.form_db_hoja1, name='form_db_hoja1'),
    path('biologia/form_fotos_bd/',views.form_fotos_db, name='form_fotos_db'),

    #Mamiferos Links
    path('biologia/form_bitacora_mamiferos/',views.form_bitacora_mamiferos, name='form_bitacora_mamiferos'),
    path('biologia/form_esfuerzo_muestreo_mamiferos/',views.form_esfuerzo_muestreo_mamiferos, name='form_esfuerzo_muestreo_mamiferos'),
    path('biologia/form_coordenadas_reporte_mamiferos/',views.form_coordenadas_reporte_mamiferos, name='form_coordenadas_reporte_mamiferos'),
    path('biologia/form_BD_mamiferos/',views.form_BD_mamiferos, name='form_BD_mamiferos'),

    #Vegetacion Links
    path('biologia/form_hoja3_vegetacion/',views.form_hoja3_vegetacion, name='form_hoja3_vegetacion'),
    path('biologia/form_Vegetacion_Compensacion_Ambiental/',views.form_Vegetacion_Compensacion_Ambiental, name='form_Vegetacion_Compensacion_Ambiental'),
    path('biologia/form_Vegetacion_Base_datos/',views.form_Vegetacion_Base_datos, name='form_Vegetacion_Base_datos'),
    path('biologia/form_Vegetacion_esfuerzo_muestreo/',views.form_Vegetacion_esfuerzo_muestreo, name='form_Vegetacion_esfuerzo_muestreo'),

    #Lista_Formularios Links
    path('biologia/list_forms_aves/',views.list_forms_Aves, name='lista_formularios_aves'),
    path('biologia/list_forms_anfibios_reptiles/',views.list_forms_Reptiles_Amfibios, name='lista_formularios_anfibios_reptiles'),
    path('biologia/list_forms_mamiferos/',views.list_forms_Mamiferos, name='lista_formularios_mamiferos'),
    path('biologia/list_forms_vegetacion/',views.list_forms_Vegetacion, name='lista_formularios_vegetacion'),

    #FORMULARIOS UNICOS - VISTA
    #Avez
    path('biologia/Avez_chinalco_BD/<id>',views.formulario_unic_Aves_chinalco, name='formulario_unic_Aves_chinalco'),
    path('biologia/Avez_chinalco_BD_coordenadas/<id>',views.formulario_unic_aves_coordenadas_int, name='formulario_unic_aves_coordenadas_int'),
    path('biologia/Avez_chinalco_BD_fotos/<id>',views.formulario_unic_Aves_chinalco_fotos, name='formulario_unic_Aves_chinalco_fotos'),

    #Anfivios

    path('biologia/Reptiles_anfibios_BD/<id>',views.formulario_unic_Reptiles_anfibios_BD, name='formulario_unic_Reptiles_anfibios_BD'),
    path('biologia/Reptiles_anfibios_BD_fotos/<id>',views.formulario_unic_Reptiles_anfibios_BD_fotos, name='formulario_unic_Reptiles_anfibios_BD_fotos'),
    path('biologia/Reptiles_anfibios_coordenadas/<id>',views.formulario_unic_Reptiles_anfibios_coordenadas, name='formulario_unic_Reptiles_anfibios_coordenadas'),
    path('biologia/Reptiles_anfibios_hoja1/<id>',views.formulario_unic_Reptiles_anfibios_BD_hoja1, name='formulario_unic_Reptiles_anfibios_BD_hoja1'),

    #Mamiferos

    path('biologia/Mamiferos_BD/<id>',views.formulario_unic_Mamiferos_BD, name='formulario_unic_Mamiferos_BD'),
    path('biologia/Mamiferos_BD_bitacora/<id>',views.formulario_unic_Mamiferos_bitacora, name='formulario_unic_Mamiferos_bitacora'),
    path('biologia/Mamiferos_BD_coordenadas/<id>',views.formulario_unic_Mamiferos_coordenadas, name='formulario_unic_Mamiferos_coordenadas'),
    path('biologia/Mamiferos_BD_esfuerzo_muestreo/<id>',views.formulario_unic_Mamiferos_ezfuerzo_muestreo, name='formulario_unic_Mamiferos_ezfuerzo_muestreo'),

    #Vegetacion

    path('biologia/Vegetacion_BD/<id>',views.formulario_unic_Vegeta_BD, name='formulario_unic_Vegeta_BD'),
    path('biologia/Vegetacion_BD_compensacion/<id>',views.formulario_unic_Vegeta_compensacion, name='formulario_unic_Vegeta_compensacion'),
    path('biologia/Vegetacion_BD_esfuerzo_muestreo/<id>',views.formulario_unic_Vegeta_esfuerzo_muestreo, name='formulario_unic_Vegeta_esfuerzo_muestreo'),
    path('biologia/Vegetacion_BD_hoja3/<id>',views.formulario_unic_Vegeta_hoja3, name='formulario_unic_Vegeta_hoja3'),



    # ========== EXPORTAR EXCEL (COMPLETO/POR UNIDAD) ============

    #===================================================#
    # Rama de Aves
    path('export/excel', views.export_aves_xls, name='export_excel'),
    path('export/excelAves', views.export_fotos_aves_xls, name='export_excel_aves'),
    path('export/excelAvesCoordenadas', views.export_coordenadas_aves_xls, name='export_excel_coordenadas_aves'),

    #Rama Unico Aves
    path('export/excelUnic/<id>', views.export_aves_unica_xls, name='export_excel_unico'),
    path('export/excelAvesUnic/<id>', views.export_fotos_aves_unica_xls, name='export_excel_aves_unico'),
    path('export/excelAvesCoordenadasUnic/<id>', views.export_coordenadas_aves_unica_xls, name='export_excel_coordenadas_aves_unic'),
    #===================================================#

    #===================================================#
    # Rama de Reptiles
    path('export/excelBDReptilesAnfibios', views.export_Anfibios_reptiles_BD_xls, name='export_excel_bd_anfibios_reptiles'),
    path('export/excelCoordenadasBDAnfiRep', views.Reporte_prueba_coordenadas, name='export_excel_coordenadas_anfi_rep'),
    path('export/excelBDFotosAnfiRep', views.export_BD_Fotos_Reptiles_Anfibios_xls, name='export_excel_fotos_bd_anfi_rep'),
    path('export/excelBDHoja1AnfiRep', views.export_BD_Hoja1_Reptiles_Anfibios_xls, name='export_excel_hoja1_bd_anfi_rep'),

    #Rama Unico Reptiles
    path('export/excelBDHoja1AnfiRep/<id>', views.export_BD_Hoja1_Reptiles_Anfibios_xls_unic, name='export_excel_hoja1_bd_anfi_rep_unic'),
    path('export/excelBDFotosAnfiRep/<id>', views.export_fotos_Reptiles_Anfibios_unico, name='exportar_fotos_Reptiles_Anfibios_unico'),
    path('export/excelCoordenadasBDAnfiRep/<id>', views.Reporte_prueba_coordenadas_unico, name='Reportar_prueba_coordenadas_unico'),
    path('export/excelBDReptilesAnfibios/<id>', views.export_Anfibios_reptiles_BD_unico, name='exportar_Anfibios_reptiles_BD_unico'),

    #===================================================#

    #===================================================#
    # Rama de Mamiferos

    path('export/excelBDMamiferos', views.export_base_datos_mamiferos, name='export_excel_bd_mamiferos'),
    path('export/excelBitacoraMamiferos', views.export_bitacora_mamiferos, name='export_excel_bitacora_mamiferos'),
    path('export/excelReporteCoordenadasMamiferos', views.export_coordenadas_reporte_mamiferos, name='export_excel_coordenadas_reporte_mamiferos'),
    path('export/excelReporteEsfuerzoMuestreoMamiferos', views.export_esfuerzo_muestreo_mamifero, name='export_excel_esfuerzo_muestreo_mamiferos'),

    #Rama Unico Mamiferos
    path('export/excelBDMamiferos/<id>', views.export_base_datos_mamiferos_unic, name='export_excel_bd_mamiferos_unic'),
    path('export/excelReporteCoordenadasMamiferos/<id>', views.export_coordenadas_reporte_mamiferos_unic, name='export_excel_coordenadas_reporte_mamiferos_unic'),
    path('export/excelEsfuerzoMuestreoMamiferos/<id>', views.export_esfuerzo_muestreo_mamiferos_unico, name='export_esfuerzo_muestreo_mamiferos_unico'),
    path('export/excelBitacoraMamiferos/<id>', views.export_bitacora_mamiferos_unico, name='export_bitacora_mamiferos_unico'),


    #===================================================#

    # Descargar Excel Rama de Vegetales
    path('export/excelHoja3', views.export_vegetacion_hoja3, name='export_excel_hoja3'),
    path('export/excelBDVegetacion', views.export_vegetacion_bd, name='export_excel_bd_vegetacion'),
    path('export/excelEsfuerzoVegetacion', views.export_vegetacion_esfuerzo, name='export_excel_esfuerzo_vegetacion'),
    path('export/excelCompensacionVegetacion', views.export_vegetacion_compensacion, name='export_excel_compensacion_vegetacion'),

    # Descargar Excel para un registro de Vegetacion
    path('export/excelHoja3Vegetacion/<id>', views.export_vegetacion_hoja3_unic, name='export_excel_vege_hoja3_unic'),
    path('export/excelEsfuerzoVegetacion/<id>', views.export_vegetacion_esfuerzo_unic, name='export_excel_vege_esfuerzo_unic'),
    path('export/excelCompensacionVegetacion/<id>', views.export_vegetacion_compensacion_unic, name='export_excel_vege_compensacion_unic'),
    path('export/excelBaseDatosVegetacion/<id>', views.export_basedatos_vegetacion_unico, name='export_basedatos_vegetacion_unico'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

walshperu/platzigram/posts/urls.py
"""Posts URLs."""

# Django
from django.urls import path

# Views
from posts import views

urlpatterns = [

    path(
        route='',
        view=views.PostsFeedView.as_view(),
        name='feed'
    ),

    path(
        route='posts/new/',
        view=views.create_post,
        name='create'
    ),
    path(
        route='posts/<int:post_id>',
        view=views.PostDetailView.as_view(),
        name='post_detail'
    ),
]

walshperu/platzigram/users/urls.py
"""Users URLs."""

# Django
from django.urls import path

# View
from users import views


urlpatterns = [

    # Management
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),
    path(
        route='me/profile/',
        view=views.UpdateProfileView.as_view(),
        name='update'
    ),

    # Posts
    path(
        route='<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    )

]

walshperu/platzigram/users/models.py
"""Users models."""

# Django
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    """Profile model.

    Proxy model that extends the base data with other
    information.
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rol = models.CharField(max_length=255, blank=True)
    departamento = models.CharField(max_length=255, blank=True)
    celular = models.IntegerField(blank=True, null=True)
    picture = models.ImageField(
        upload_to='users/pictures',
        blank=True,
        null=True
    )

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return username."""
        return self.user.username

walshperu/platzigram/users/forms.py
"""User forms."""

# Django
from django import forms

# Models
from django.contrib.auth.models import User
from users.models import Profile


class SignupForm(forms.Form):
    """Sign up form."""

    username = forms.CharField(
        label=False,
        min_length=4, 
        max_length=50,
        widget=forms.TextInput(attrs={
            'placeholder': 'Nombre de usuario',
            'class': 'form-control',
            'required': True
            })
        )

    password = forms.CharField(
        label=False,
        max_length=70,
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Escribe tu contraseña',
            'class': 'form-control',
            'required': True
            })
    )
    password_confirmation = forms.CharField(
        label=False,
        max_length=70,
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Confirma tu contraseña',
            'class': 'form-control',
            'required': True
            })
    )

    first_name = forms.CharField(
        label=False,
        min_length=2, 
        max_length=50,
        widget=forms.TextInput(attrs={
            'placeholder': 'Nombre',
            'class': 'form-control',
            'required': True
            })
        )
    last_name = forms.CharField(
        label=False,
        min_length=2, 
        max_length=50,
        widget=forms.TextInput(attrs={
            'placeholder': 'Apellido',
            'class': 'form-control',
            'required': True
            })
        )

    email = forms.CharField(
        label=False,
        min_length=6,
        max_length=70,
        widget=forms.EmailInput(attrs={
            'placeholder': 'Correo electronico',
            'class': 'form-control',
            'required': True
            })
    )

    def clean_username(self):
        """Username must be unique."""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use.')
        return username

    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match.')

        return data

    def save(self):
        """Create user and profile."""
        data = self.cleaned_data
        data.pop('password_confirmation')

        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()


class ProfileForm(forms.Form):
    """Profile form."""

    website = forms.URLField(max_length=200, required=True)
    biography = forms.CharField(max_length=500, required=False)
    phone_number = forms.CharField(max_length=20, required=False)
    picture = forms.ImageField()

walshperu/platzigram/users/views.py
"""Users views."""

# Django
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, FormView, UpdateView

# Models
from django.contrib.auth.models import User
from posts.models import Post
from users.models import Profile

# Forms
from users.forms import SignupForm


class UserDetailView(LoginRequiredMixin, DetailView):
    """User detail view."""

    template_name = 'users/detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    queryset = User.objects.all()
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        """Add user's posts to context."""
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['posts'] = Post.objects.filter(user=user).order_by('-created')
        return context


class SignupView(FormView):
    """Users sign up view."""

    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """Save form data."""
        form.save()
        return super().form_valid(form)


class UpdateProfileView(LoginRequiredMixin, UpdateView):
    """Update profile view."""

    template_name = 'users/update_profile.html'
    model = Profile
    fields = ['website', 'biography', 'phone_number', 'picture']

    def get_object(self):
        """Return user's profile."""
        return self.request.user.profile

    def get_success_url(self):
        """Return to user's profile."""
        username = self.object.user.username
        return reverse('users:detail', kwargs={'username': username})

class LoginView(auth_views.LoginView):

    template_name = 'users/login-v2.html'
    redirect_authenticated_user = True

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['username'].widget.attrs.update({
            'class': 'form-control'})
        form.fields['password'].widget.attrs.update({
            'class': 'form-control'})
        return form

    def get(self, request, *args, **kwargs):
        """Handle GET requests: instantiate a blank version of the form."""
        if request.user.is_authenticated:
            return redirect('posts:feed')
        return super().get(request, args, kwargs)



class LogoutView(LoginRequiredMixin, auth_views.LogoutView):

    template_name = 'users/logget_out.html'

walshperu/platzigram/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body class="h-100">

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">

                <img src="{% static "img/instagram.png" %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">

                {% block container %}{% endblock%}

            </div>
        </div>
    </div>

</body>
</html>

walshperu/platzigram/templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ user.username }} | Andregram</title>
{% endblock %}

{% block container %}

    <div class="container mb-5" style="margin-top: 8em;">
        <div class="row">
            <div class="col-sm-4 d-flex justify-content-center">
                <img src="{{ user.profile.picture.url }}" alt="@{{ user.username }}"class="rounded-circle"width="150px" />
            </div>
            <div class="col-sm-8">
                <h2 style="font-weight: 100;">
                    {{ user.username }}
                    {% if user == request.user %}
                        <a
                            href="{% url "users:update" %}"
                            class="ml-5 btn btn-sm btn-outline-info"
                        >
                            Edit profile
                        </a>
                    {% else %}
                        <a
                            href=""
                            class="ml-5 btn btn-sm btn-primary"
                        >
                            Follow
                        </a>
                    {% endif %}
                </h2>
                <div class="row mt-2"style="font-size: 1.2em">
                    <div class="col-sm-4">
                        <b>{{ user.profile.posts_count }}785</b> posts
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.followers }}1,401</b> followers
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.following }}491</b> following
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-sm-12">
                        <p>{{ user.profile.biography }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr>

<div class="container" id="user-posts">
        <div class="row mt-3">
            {% for post in posts %}
            <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
               <a href="{% url "posts:post_detail" post.id%}"class="border">
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid"/>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

walshperu/platzigram/templates/users/login-v2.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Walsh Peru | Login</title>
  
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- icheck bootstrap -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- Theme style -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/adminlte.min.css' %}">

  <!-- Estilos Principales -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/estilos-login.css' %}">

</head>
<body class="hold-transition pagina-login" style="background-image: url({% static 'img/amazona-iquitos-peru_55cfe9cc.png' %})" >

<div class="login-box">
  <!-- /.login-logo -->
  <div class="card card-outline card-success">
    <div class="card-header text-center">
      <a href="#" class="h1"><img width="100%" src="{% static 'img/logo2.0.jpg' %}" alt=""></a>
    </div>
    <div class="card-body">
      <p class="login-box-msg"><b>Iniciar Sesion</b></p>

      <form method="POST" action="{% url "users:login" %}">
         {% csrf_token %}
        <div class="input-group mb-3">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
          <input type="text" class="form-control" name="username" placeholder="Usuario">
          
        </div>
        <div class="input-group mb-3">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
          <input type="password" class="form-control" name="password" placeholder="Contraseña">
          
        </div>
        <div class="row justify-content-center align-items-center">
          
          <!-- <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="remember">
              <label for="remember">
                Remember Me
              </label>
            </div>
          </div> -->

          <!-- /.col -->
          <div class="col-6 mt-2">
            <button style="background-color: #327d6f;" type="submit" class="btn btn-success btn-block">Iniciar sesion</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <!-- /.social-auth-links -->
    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->
</div>
<!-- /.login-box -->

<!-- jQuery -->
{% block javascript %}
<script src="plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="js/adminlte.min.js"></script>
 {% endblock %}

</body>
</html>

walshperu/platzigram/templates/users/login.html
{% extends "users/base.html" %}

{% block head_content %}
<title>Andregram | Inicio de sesión</title>
{% endblock%}

{% block container %}

    {% if form_errors %}
        <p class="alert alert-danger">Your username and password didnt match. Try again.</p>
    {% endif%}

    <form method="POST" action="{% url "users:login" %}">
        {% csrf_token %}

        <div class="form-group">
            <input class="form-control" type="text" placeholder="Usuario" name="username" />
        </div>

        <div class="form-group">
            <input class="form-control" type="password" placeholder="Contraseña" name="password" />
        </div>


        <button class="btn btn-primary btn-block mt-5" type="submit">Sign in!</button>

    </form>

    <p class="mt-4">No tienes una cuenta aún? <a href="{% url "users:signup" %}">Registrate aquí</a></p>

{% endblock %}

walshperu/platzigram/templates/users/signup.html
{% extends "users/base.html" %}

{% block head_content %}
<title>Andregram registrarse</title>
{% endblock %}

{% block container %}

    <form action="{% url 'users:signup' %}" method="POST">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="btn btn-primary btn-block mt-5" type="submit">Registrate!</button>

    </form>

{% endblock %}

walshperu/platzigram/templates/users/update_profile.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{ request.user.username }} | Actualizar usuario</title>
{% endblock %}

{% block container %}

<div class="container">

    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">

            <form action="{% url 'users:update' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="media">
                    {% if profile.picture %}
                        <img src="{{ profile.picture.url }}" class="rounded-circle" height="50" />
                    {% else%}
                        <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50" />
                    {% endif %}

                    <div class="media-body">
                        <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
                        <p class="ml-4"><input type="file" name="picture"></p>
                    </div>
                </div>

                {% for error in form.picture.errors %}
                <div class="alert alert-danger">
                    <b>Picture: </b>{{ error }}
                </div>
                {% endfor %}

                <hr><br>

                {# Website field #}
                <div class="form-group">
                    <label>Sitio Web</label>
                    <input
                        class="form-control {% if form.website.errors %}is-invalid{% endif %}"
                        type="text"
                        name="website"
                        placeholder="Enlace a tu página"
                        value="{% if form.errors %}{{ form.website.value }}{% else %}{{ profile.website }}{% endif %}"
                    />
                    <div class="invalid-feedback">
                        {% for error in form.website.errors %}
                            {{ error }}
                        {% endfor%}
                    </div>
                </div>

                {# Biography field #}
                <div class="form-group">
                    <label>Biografía</label>
                    <textarea
                        class="form-control {% if form.biography.errors %}is-invalid{% endif %}"
                        name="biography"
                    >{% if form.errors %}{{ form.biography.value }}{% else %}{{ profile.biography }}{% endif %}</textarea>

                    <div class="invalid-feedback">
                        {% for error in form.biography.errors %}
                            {{ error }}
                        {% endfor%}
                    </div>
                </div>

                {# Phone number field #}
                <div class="form-group">
                    <label>Número de celular</label>
                    <input
                        class="form-control {% if form.phone_number.errors %}is-invalid{% endif %}"
                        type="text"
                        name="phone_number"
                        placeholder="Celular"
                        value="{% if form.errors %}{{ form.phone_number.value }}{% else %}{{ profile.phone_number }}{% endif %}"
                    />
                    <div class="invalid-feedback">
                        {% for error in form.phone_number.errors %}
                            {{ error }}
                        {% endfor%}
                    </div>
                </div>

                <button type="submit" class="btn btn-primary btn-block mt-5">Actualizar perfil</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}