walshperu/platzigram/platzigram/urls.py
"""Platzigram URLs module."""

# Django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from biologia import views


urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('users/', include(('users.urls', 'users'), namespace='users')),

    #Avez Links
    path('biologia/form_coordenadas_aves/',views.form_coordenadas_aves, name='form_coordenadas_aves'),
    path('biologia/form_base_datos_avez/',views.form_BD_Avez_Chinalco, name='form_BD_Avez_Chinalco'),
    path('biologia/form_fotos_integrado_avez/',views.form_fotos_integrado_Avez_Chinalco, name='form_fotos_integrado_Avez_Chinalco'),

    #Anfivioz_Reptiles (BD) Links
    path('biologia/form_base_anfibios_reptiles/',views.form_anfibios_reptiles_base_datos, name='form_anfibios_reptiles_base_datos'),
    path('biologia/form_coord_anf_rep/',views.form_coordenadas_anfibios_repites_bd, name='form_coordenadas_anfibios_repites_bd'),
    path('biologia/form_hoja_1/',views.form_db_hoja1, name='form_db_hoja1'),
    path('biologia/form_fotos_bd/',views.form_fotos_db, name='form_fotos_db'),

    #Mamiferos Links
    path('biologia/form_bitacora_mamiferos/',views.form_bitacora_mamiferos, name='form_bitacora_mamiferos'),
    path('biologia/form_esfuerzo_muestreo_mamiferos/',views.form_esfuerzo_muestreo_mamiferos, name='form_esfuerzo_muestreo_mamiferos'),
    path('biologia/form_coordenadas_reporte_mamiferos/',views.form_coordenadas_reporte_mamiferos, name='form_coordenadas_reporte_mamiferos'),
    path('biologia/form_BD_mamiferos/',views.form_BD_mamiferos, name='form_BD_mamiferos'),

    #Vegetacion Links
    path('biologia/form_hoja3_vegetacion/',views.form_hoja3_vegetacion, name='form_hoja3_vegetacion'),
    path('biologia/form_Vegetacion_Compensacion_Ambiental/',views.form_Vegetacion_Compensacion_Ambiental, name='form_Vegetacion_Compensacion_Ambiental'),
    path('biologia/form_Vegetacion_Base_datos/',views.form_Vegetacion_Base_datos, name='form_Vegetacion_Base_datos'),
    path('biologia/form_Vegetacion_esfuerzo_muestreo/',views.form_Vegetacion_esfuerzo_muestreo, name='form_Vegetacion_esfuerzo_muestreo'),

    #Lista_Formularios Links
    path('biologia/list_forms_aves/',views.list_forms_Aves, name='lista_formularios_aves'),
    path('biologia/list_forms_anfibios_reptiles/',views.list_forms_Reptiles_Amfibios, name='lista_formularios_anfibios_reptiles'),
    path('biologia/list_forms_mamiferos/',views.list_forms_Mamiferos, name='lista_formularios_mamiferos'),
    path('biologia/list_forms_vegetacion/',views.list_forms_Vegetacion, name='lista_formularios_vegetacion'),

    #FORMULARIOS UNICOS - VISTA
    #Avez
    path('biologia/Avez_chinalco_BD/<id>',views.formulario_unic_Aves_chinalco, name='formulario_unic_Aves_chinalco'),
    path('biologia/Avez_chinalco_BD_coordenadas/<id>',views.formulario_unic_aves_coordenadas_int, name='formulario_unic_aves_coordenadas_int'),
    path('biologia/Avez_chinalco_BD_fotos/<id>',views.formulario_unic_Aves_chinalco_fotos, name='formulario_unic_Aves_chinalco_fotos'),

    #Anfivios

    path('biologia/Reptiles_anfibios_BD/<id>',views.formulario_unic_Reptiles_anfibios_BD, name='formulario_unic_Reptiles_anfibios_BD'),
    path('biologia/Reptiles_anfibios_BD_fotos/<id>',views.formulario_unic_Reptiles_anfibios_BD_fotos, name='formulario_unic_Reptiles_anfibios_BD_fotos'),
    path('biologia/Reptiles_anfibios_coordenadas/<id>',views.formulario_unic_Reptiles_anfibios_coordenadas, name='formulario_unic_Reptiles_anfibios_coordenadas'),
    path('biologia/Reptiles_anfibios_hoja1/<id>',views.formulario_unic_Reptiles_anfibios_BD_hoja1, name='formulario_unic_Reptiles_anfibios_BD_hoja1'),

    #Mamiferos

    path('biologia/Mamiferos_BD/<id>',views.formulario_unic_Mamiferos_BD, name='formulario_unic_Mamiferos_BD'),
    path('biologia/Mamiferos_BD_bitacora/<id>',views.formulario_unic_Mamiferos_bitacora, name='formulario_unic_Mamiferos_bitacora'),
    path('biologia/Mamiferos_BD_coordenadas/<id>',views.formulario_unic_Mamiferos_coordenadas, name='formulario_unic_Mamiferos_coordenadas'),
    path('biologia/Mamiferos_BD_esfuerzo_muestreo/<id>',views.formulario_unic_Mamiferos_ezfuerzo_muestreo, name='formulario_unic_Mamiferos_ezfuerzo_muestreo'),

    #Vegetacion

    path('biologia/Vegetacion_BD/<id>',views.formulario_unic_Vegeta_BD, name='formulario_unic_Vegeta_BD'),
    path('biologia/Vegetacion_BD_compensacion/<id>',views.formulario_unic_Vegeta_compensacion, name='formulario_unic_Vegeta_compensacion'),
    path('biologia/Vegetacion_BD_esfuerzo_muestreo/<id>',views.formulario_unic_Vegeta_esfuerzo_muestreo, name='formulario_unic_Vegeta_esfuerzo_muestreo'),
    path('biologia/Vegetacion_BD_hoja3/<id>',views.formulario_unic_Vegeta_hoja3, name='formulario_unic_Vegeta_hoja3'),



    # ========== EXPORTAR EXCEL (COMPLETO/POR UNIDAD) ============

    #===================================================#
    # Rama de Aves
    path('export/excel', views.export_aves_xls, name='export_excel'),
    path('export/excelAves', views.export_fotos_aves_xls, name='export_excel_aves'),
    path('export/excelAvesCoordenadas', views.export_coordenadas_aves_xls, name='export_excel_coordenadas_aves'),

    #Rama Unico Aves
    path('export/excelUnic/<id>', views.export_aves_unica_xls, name='export_excel_unico'),
    path('export/excelAvesUnic/<id>', views.export_fotos_aves_unica_xls, name='export_excel_aves_unico'),
    path('export/excelAvesCoordenadasUnic/<id>', views.export_coordenadas_aves_unica_xls, name='export_excel_coordenadas_aves_unic'),
    #===================================================#

    #===================================================#
    # Rama de Reptiles
    path('export/excelBDReptilesAnfibios', views.export_Anfibios_reptiles_BD_xls, name='export_excel_bd_anfibios_reptiles'),
    path('export/excelCoordenadasBDAnfiRep', views.Reporte_prueba_coordenadas, name='export_excel_coordenadas_anfi_rep'),
    path('export/excelBDFotosAnfiRep', views.export_BD_Fotos_Reptiles_Anfibios_xls, name='export_excel_fotos_bd_anfi_rep'),
    path('export/excelBDHoja1AnfiRep', views.export_BD_Hoja1_Reptiles_Anfibios_xls, name='export_excel_hoja1_bd_anfi_rep'),

    #Rama Unico Reptiles
    path('export/excelBDHoja1AnfiRep/<id>', views.export_BD_Hoja1_Reptiles_Anfibios_xls_unic, name='export_excel_hoja1_bd_anfi_rep_unic'),
    path('export/excelBDFotosAnfiRep/<id>', views.export_fotos_Reptiles_Anfibios_unico, name='exportar_fotos_Reptiles_Anfibios_unico'),
    path('export/excelCoordenadasBDAnfiRep/<id>', views.Reporte_prueba_coordenadas_unico, name='Reportar_prueba_coordenadas_unico'),
    path('export/excelBDReptilesAnfibios/<id>', views.export_Anfibios_reptiles_BD_unico, name='exportar_Anfibios_reptiles_BD_unico'),

    #===================================================#

    #===================================================#
    # Rama de Mamiferos

    path('export/excelBDMamiferos', views.export_base_datos_mamiferos, name='export_excel_bd_mamiferos'),
    path('export/excelBitacoraMamiferos', views.export_bitacora_mamiferos, name='export_excel_bitacora_mamiferos'),
    path('export/excelReporteCoordenadasMamiferos', views.export_coordenadas_reporte_mamiferos, name='export_excel_coordenadas_reporte_mamiferos'),
    path('export/excelReporteEsfuerzoMuestreoMamiferos', views.export_esfuerzo_muestreo_mamifero, name='export_excel_esfuerzo_muestreo_mamiferos'),

    #Rama Unico Mamiferos
    path('export/excelBDMamiferos/<id>', views.export_base_datos_mamiferos_unic, name='export_excel_bd_mamiferos_unic'),
    path('export/excelReporteCoordenadasMamiferos/<id>', views.export_coordenadas_reporte_mamiferos_unic, name='export_excel_coordenadas_reporte_mamiferos_unic'),
    path('export/excelEsfuerzoMuestreoMamiferos/<id>', views.export_esfuerzo_muestreo_mamiferos_unico, name='export_esfuerzo_muestreo_mamiferos_unico'),
    path('export/excelBitacoraMamiferos/<id>', views.export_bitacora_mamiferos_unico, name='export_bitacora_mamiferos_unico'),


    #===================================================#

    # Descargar Excel Rama de Vegetales
    path('export/excelHoja3', views.export_vegetacion_hoja3, name='export_excel_hoja3'),
    path('export/excelBDVegetacion', views.export_vegetacion_bd, name='export_excel_bd_vegetacion'),
    path('export/excelEsfuerzoVegetacion', views.export_vegetacion_esfuerzo, name='export_excel_esfuerzo_vegetacion'),
    path('export/excelCompensacionVegetacion', views.export_vegetacion_compensacion, name='export_excel_compensacion_vegetacion'),

    # Descargar Excel para un registro de Vegetacion
    path('export/excelHoja3Vegetacion/<id>', views.export_vegetacion_hoja3_unic, name='export_excel_vege_hoja3_unic'),
    path('export/excelEsfuerzoVegetacion/<id>', views.export_vegetacion_esfuerzo_unic, name='export_excel_vege_esfuerzo_unic'),
    path('export/excelCompensacionVegetacion/<id>', views.export_vegetacion_compensacion_unic, name='export_excel_vege_compensacion_unic'),
    path('export/excelBaseDatosVegetacion/<id>', views.export_basedatos_vegetacion_unico, name='export_basedatos_vegetacion_unico'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

walshperu/platzigram/posts/urls.py
"""Posts URLs."""

# Django
from django.urls import path

# Views
from posts import views

urlpatterns = [

    path(
        route='',
        view=views.PostsFeedView.as_view(),
        name='feed'
    ),

    path(
        route='posts/new/',
        view=views.create_post,
        name='create'
    ),
    path(
        route='posts/<int:post_id>',
        view=views.PostDetailView.as_view(),
        name='post_detail'
    ),
]

walshperu/platzigram/users/urls.py
"""Users URLs."""

# Django
from django.urls import path

# View
from users import views


urlpatterns = [

    # Management
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),
    path(
        route='me/profile/',
        view=views.UpdateProfileView.as_view(),
        name='update'
    ),

    # Posts
    path(
        route='<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    )

]

walshperu/platzigram/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}
    {% endblock %}


    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body>

    {% include "nav.html" %}

    <div class="container mt-5">
        {% block container %}
    <h1>dsadasdasdasd</h1>
        {% endblock%}
    </div>

</body>
</html>

walshperu/platzigram/templates/footer.html
<footer class="main-footer">
    <div class="float-right d-none d-sm-block">
        <b>Version</b> PreAphal 0.0.1
    </div>
    <strong>Copyright &copy; 2020-2021 <a href="http://www.walshp.com.pe/">WalshPeru</a>.</strong> Todos los derechos resevados.
</footer>

walshperu/platzigram/templates/hola.html
<h3>Hola</h3>

walshperu/platzigram/templates/messages.html
{% for message in messages %}
<div class="container-fluid p-0">
    <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
    </div>
</div>
{% endfor %}

walshperu/platzigram/templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
    <div class="container">

        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url "posts:feed" %}">
            <img src="{% static "img/instagram.png" %}" height="45" class="d-inline-block align-top"/>
        </a>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a href="{% url "users:detail" request.user.username %}">
                        {% if request.user.profile.picture %}
                            <img src="{{ request.user.profile.picture.url }}" height="35" class="d-inline-block align-top rounded-circle"/>
                        {% else%}
                            <img src="{% static 'img/default-profile.png' %}" height="35" class="d-inline-block align-top rounded-circle"/>
                        {% endif %}
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url "posts:create" %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url "users:logout" %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>

walshperu/platzigram/templates/navbar.html
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>

        </li>

    </ul>
    <ul class="navbar-nav ml-auto">
        <h4>Walsh Perú</h4>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="fas fa-th-large"></i>
            </a>
        </li>
    </ul>
</nav>

walshperu/platzigram/templates/pagination.html
<nav>
    <ul class="pagination justify-content-end">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Previous
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" href="#">
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Next
            </a>
        </li>
        {% endif %}
    </ul>
</nav>

walshperu/platzigram/templates/rel.html
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<!-- Font Awesome -->
{% load static %}
<link rel="shortcut icon" type="image/x-icon" href="{% static 'admin-lte/dist/img/logowalsh.jpg' %}">

<link rel="stylesheet" href="{% static 'admin-lte/plugins/fontawesome-free/css/all.min.css' %}">
<!-- daterange picker -->
<link rel="stylesheet" href="{% static 'admin-lte/plugins/daterangepicker/daterangepicker.css' %}">
<!-- iCheck for checkboxes and radio inputs -->
<link rel="stylesheet" href="{% static 'admin-lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
<!-- Bootstrap Color Picker -->
<link rel="stylesheet" href="{% static 'admin-lte/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css' %}">
<!-- Tempusdominus Bootstrap 4 -->
<link rel="stylesheet" href="{% static 'admin-lte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
<!-- Select2 -->
<link rel="stylesheet" href="{% static 'admin-lte/plugins/select2/css/select2.min.css' %}">
<link rel="stylesheet" href="{% static 'admin-lte/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css' %}">
<!-- Bootstrap4 Duallistbox -->
<link rel="stylesheet" href="{% static 'admin-lte/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css' %}">
<!-- BS Stepper -->
<link rel="stylesheet" href="{% static 'admin-lte/plugins/bs-stepper/css/bs-stepper.min.css' %}">
<!-- dropzonejs -->
<link rel="stylesheet" href="{% static 'admin-lte/plugins/dropzone/min/dropzone.min.css' %}">
<!-- Theme style -->
<link rel="stylesheet" href="{% static 'admin-lte/dist/css/adminlte.min.css' %}">

walshperu/platzigram/templates/sidebar.html
{% load static %}

<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{% url 'posts:feed' %}" class="brand-link">
        <img src="{% static 'admin-lte/dist/img/logowalsh.jpg' %}"  class="brand-image img-circle elevation-3" style="opacity: 1">
        <span class="brand-text font-weight-light">Walsh Perú</span>
    </a>
    <a href="#" class="brand-link">
        <img src="{% static 'admin-lte/dist/img/biologia.png' %}" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">{{request.user.profile.departamento}}</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar" >
        <!-- Sidebar user panel (optional) -->

        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{ request.user.profile.picture.url }}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{request.user.first_name}} {{request.user.last_name}}</a>
            </div>
        </div>

        <!-- SidebarSearch Form -->


        <!-- Sidebar Menu -->
        <nav class="mt-4" >
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false" >

                <li class="nav-item menu" style="width: 100%">
                    <a href="#" class="nav-link active bg-info">
                        <i class="nav-icon fas fa-edit"></i>
                        <p>
                            Formularios
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    {% if request.user.profile.departamento == "Biología" %}
                    <ul class="nav nav-treeview">
                        <li class="nav-item" >
                            <a href="{% url 'form_BD_Avez_Chinalco' %}" class=" nav-link ">
                                <span class="d-inline-block text-truncate" style="max-width: 200px;">
                                    Aves Chinalco 2018
                                </span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'form_fotos_integrado_Avez_Chinalco' %}" class="nav-link">
                                <span class="d-inline-block text-truncate" style="max-width: 200px;">
                                    Fotos Integrado Aves Chinalco
                                </span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'form_coordenadas_aves' %}" class="nav-link">
                                <span class="d-inline-block text-truncate" style="max-width: 200px;">
                                    Coordenadas Integradas Aves
                                </span>
                            </a>
                        </li>
                        <hr size="2px" style="color: #000000;"/>
                        <li class="nav-item">
                            <a href="{% url 'form_anfibios_reptiles_base_datos' %}" class="nav-link">
                                <span class="d-inline-block text-truncate" style="max-width: 200px;">
                                    Anfibios y Reptiles Base de Datos
                                </span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'form_coordenadas_anfibios_repites_bd' %}" class="nav-link">
                                <span class="d-inline-block text-truncate" style="max-width: 200px;">
                                    Coordenadas Anfibios y Reptiles
                                </span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'form_db_hoja1' %}" class="nav-link">
                                <span class="d-inline-block text-truncate" style="max-width: 200px;">
                                    Hoja1 BD
                                </span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'form_fotos_db' %}" class="nav-link">
                                <span class="d-inline-block text-truncate" style="max-width: 200px;">
                                    Fotos BD Reptiles y Anfibios
                                </span>
                            </a>
                        </li>
                        <hr size="2px" style="color: #000000;"/>
                        <li class="nav-item">
                            <a href="{% url 'form_bitacora_mamiferos' %}" class="nav-link">
                                <span class="d-inline-block text-truncate" style="max-width: 200px;">
                                    Bitacora Mamiferos
                                </span>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="{% url 'form_coordenadas_reporte_mamiferos' %}" class="nav-link">
                                <span class="d-inline-block text-truncate" style="max-width: 200px;">
                                    Coordenadas Reporte Mamiferos
                                </span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'form_esfuerzo_muestreo_mamiferos' %}" class="nav-link">
                                <span class="d-inline-block text-truncate" style="max-width: 200px;">
                                    Esfuerzo muestreo Mamiferos
                                </span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'form_BD_mamiferos' %}" class="nav-link">
                                <span class="d-inline-block text-truncate" style="max-width: 200px;">
                                   Base de Datos de Mamiferos
                                </span>
                            </a>
                        </li>
                        <hr size="2px" style="color: #000000;"/>
                        <li class="nav-item">
                            <a href="{% url 'form_hoja3_vegetacion' %}" class="nav-link">
                                <span class="d-inline-block text-truncate" style="max-width: 200px;">
                                    Hoja3 Vegetacion
                                </span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'form_Vegetacion_Compensacion_Ambiental' %}" class="nav-link">
                                <span class="d-inline-block text-truncate" style="max-width: 200px;">
                                    Compensacion Ambiental
                                </span>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="{% url 'form_Vegetacion_Base_datos' %}" class="nav-link">
                                <span class="d-inline-block text-truncate" style="max-width: 200px;">
                                    Vegetacion Base de Datos.
                                </span>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="{% url 'form_Vegetacion_esfuerzo_muestreo' %}" class="nav-link">
                                <span class="d-inline-block text-truncate" style="max-width: 200px;">
                                    Vegetacion Esfuerzo.
                                </span>
                            </a>
                        </li>
                        <hr size="2px" style="color: #000000;"/>
                    </ul>
                    {% else%}
                <li class="nav-item" >
                    <a href="#" class=" nav-link ">
                                <span class="d-inline-block text-truncate" style="max-width: 200px;">
                                    No tienes departamento.
                                </span>
                    </a>
                </li>
                    {% endif %}
                </li>
                <li class="nav-item menu" style="width: 100%">
                    <a href="#" class="nav-link active">
                        <i class="nav-icon fas fa-file-alt"></i>
                        <p>
                            Ver Reportes
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    {% if request.user.profile.departamento == "Biología" %}
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url 'lista_formularios_aves' %}" class="nav-link ">
                                <i class="fas fa-angle-right"></i>
                                <p>Proyecto MIN1711</p>
                            </a>
                        </li>

                    </ul>
                    {% else%}
                <li class="nav-item" >
                    <a href="#" class=" nav-link ">
                                <span class="d-inline-block text-truncate" style="max-width: 200px;">
                                    No tienes departamento.
                                </span>
                    </a>
                </li>
                {% endif %}
                </li>
                <li class="nav-item menu " style="width: 100%">
                    <a href="{% url 'users:logout' %}" class="nav-link active bg-danger">
                        <i class="nav-icon fas fa-sign-out-alt"></i>
                        <p>Salir</p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>